### ISSUE TITLE
스켈레톤 작성

### ISSUE THREAD

**Issue by gpfud1998** [gpfud1998/JangChangMin_cal#1]
프로젝트 시작

**Comment by seongminKwon99** [comment]
int add(int,int);
int sub(int,int);
int div(int, int);
int multi(int, int);

int main(int argc, char* argv[]){
    int a, b,c;
    char operator;

    printf("Please enter a expression");
    scanf("%d %c %d", &a, &operator, &b);

    switch(operator){
        case '+': c = add(a,b); break;
        case '-': c = sub(a,b); break;
        case '*': c = multi(a,b); break;
    }
}
